## <span style="color:blue">Numpy Parte I - Exercícios</span>

**Maurício Luiz Sobrinho**<br>


#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>


In [ ]:
import numpy as np

### Exercício 1)

Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.


In [ ]:
x = np.random.randint(0, 20, 30).reshape(5, 6)
print(x)

### Exercício 2)

Crie uma **view** da matriz `A` gerada na célula anterior contendo:

- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3


In [ ]:
print(x)
y = x[[0, 1, 3], :]
t = x[1:3, [0, 2, 4]]
x = x[[1, 3]][:, [1, 3]]

print("Resultado - 1\n", y)
print("Resultado - 2", t)
print("Resultado - 3", x)

### Exercício 3)

Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20.

- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1

**Dica:** Gere máscaras booleanas para realizar as modificações nos arrays.


In [ ]:
a = np.random.randint(0, 20, 30).reshape(5, 6)
print("Antes: \n", a)
ac = a.flatten().reshape(5, 6)
mask_a = a > 10
mask_ac = (ac > 7) & (ac < 15)


a[mask_a] = -1
ac[mask_ac] = -1

print("Resultado de (A) com -1: \n", a)
print("Resultado de (Ac) com -1: \n", ac)

### Exercício 4)

Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de 1 até 200.

- Crie uma **view** de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par.
- Crie uma **view** de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar.


In [ ]:
a = np.array(range(1, 201)).reshape(20, 10)
print("Antes \n", a)
a_lpares = a[::2]
a_lpares_cimpares = a[::2, ::2]

print("Par \n", a_lpares)
print("Pares linhas e Impar colunas \n", a_lpares_cimpares)

### Exercício 5)

Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par.

**Dica:** Construa uma máscara booleana


In [ ]:
rows, col = np.indices(a.shape)
mask_lapares = (rows % 2 == 0) | (col % 2 == 0)

a[mask_lapares] = -1
print("Par -1 \n", a)

### Exercício 6)

Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

**Dica:** Converta o array em uma lista e ordene.


In [22]:
a = np.random.uniform(0, 1, 30).reshape(6, 5)
x_sorted = sorted(a.ravel())
print("Eixo: \n", x_sorted[:3])

Eixo: 
 [0.007185433558302479, 0.2522359121701042, 0.25243157178136666]


### Exercício 7)

Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:

```python
X = np.array([[0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```

deve resultar em

```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [ ]:
x = np.array([[0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5]])


def troca_colunas(x_array, col1, col2):
    x_transpose = x_array.T
    x_transpose[col1], x_transpose[col2] = x_transpose[col2].copy(
    ), x_transpose[col1].copy()
    return x_transpose.T


troca_x = troca_colunas(x, 1, 3)
print(troca_x)

### Exercício 8)

Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:

```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```

deve resultar em

```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```


In [ ]:
data = np.array([[2, 8, 3, 4, 8],
                 [4, 8, 7, 7, 3],
                 [8, 2, 3, 1, 4],
                 [8, 6, 3, 8, 1],
                 [6, 4, 4, 6, 1]])

# Com método triu
result = np.triu(data)
print("Com método do numpy: \n", result)


# Percorrendo a matriz
data_nomethod = data.copy()

rows, cols = data_nomethod.shape
for i in range(1, rows):
    for j in range(i):
        data_nomethod[i, j] = 0

print("Sem o método: \n", data_nomethod)